name: gaggamagga CD

on:
  push:
    branches: ['main']

jobs:
  deploy:
    name: CD Pipeline
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11.0"]

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          key: ${{ secrets.EC2_KEY }}
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_NAME }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd ${{ secrets.EC2_PATH }}
            git pull origin main
            cd ../../
            sudo docker compose stop backend
            sudo docker compose restart backend
